### ISSUE TITLE
Add some other sorting Algorithms

### ISSUE THREAD

**Issue by vigneshs-dev** [FerdausPolok/dev-mates#26]
Hi @FerdausPolok ,
I have forked your repository, created a branch and added some other sorting algorithms. Can you assign this task to me with hacktoberfest tag, so that I can create a Pull Request? 
Thankyou.

**Comment by FerdausPolok** [comment]
> Hi @FerdausPolok , I have forked your repository, created a branch and added some other sorting algorithms. Can you assign this task to me with hacktoberfest tag, so that I can create a Pull Request? Thankyou.

Hello @vigneshs-dev,
Thanks for your interest. I've assigned you into this issue and I don't think it's necessary to add tag here. Feel free to open PR and add me as reviewer. Thanks.

**Comment by vigneshs-dev** [comment]
> > Hi @FerdausPolok , I have forked your repository, created a branch and added some other sorting algorithms. Can you assign this task to me with hacktoberfest tag, so that I can create a Pull Request? Thankyou.
> 
> Hello @vigneshs-dev, Thanks for your interest. I've assigned you into this issue and I don't think it's necessary to add tag here. Feel free to open PR and add me as reviewer. Thanks.

How can I add you as a Reviewer for my Pull Request. I searched the web. But I didn't get any solution. When I try to Open a Pull Request, it wants a reviewer. Can you please explain the steps?

**Comment by FerdausPolok** [comment]
> > > Hi @FerdausPolok , I have forked your repository, created a branch and added some other sorting algorithms. Can you assign this task to me with hacktoberfest tag, so that I can create a Pull Request? Thankyou.
> > 
> > 
> > Hello @vigneshs-dev, Thanks for your interest. I've assigned you into this issue and I don't think it's necessary to add tag here. Feel free to open PR and add me as reviewer. Thanks.
> 
> How can I add you as a Reviewer for my Pull Request. I searched the web. But I didn't get any solution. When I try to Open a Pull Request, it wants a reviewer. Can you please explain the steps?

![image](https://github.com/user-attachments/assets/41c1df97-573e-4400-a3e2-fc4775ceebf2)

**Comment by vigneshs-dev** [comment]
That settings button is not showing to me.

![Pull_Request_Reviewer](https://github.com/user-attachments/assets/16fd1825-7e69-40e5-8e7c-7283837bc01f)

I think only the owner has the authority to set the reviewer.
