### ISSUE TITLE
Further update youtube session manager to next level

### ISSUE THREAD

**Issue by tanushrigoel** [FerdausPolok/dev-mates#33]
## Overview

After the recent updates to the **TabTime Guardian** extension, we need to ensure that the timer functionality is improved and applies only to specific websites. This issue will track the implementation of the following changes and enhancements:

### Tasks:
1. **Scope Timer to Specific Websites**:
   - Ensure the timer functionality only applies to designated websites (e.g., YouTube).
   - Currently, the timer applies to all websites, which needs to be restricted.

2. **Button Interactions**:
   - Ensure that the `+` and `-` buttons to increment or decrement the timer are fully functional while the timer is active.
   - Disable the decrement button when the timer reaches 0 to prevent negative values.

3. **"Reset" Button Enhancement**:
   - Implement a fully functional "Reset" button that allows users to clear the active timer and set a new one without reloading the page.

4. **Improve Visual Feedback**:
   - Provide visual feedback for the user when the timer is adjusted or reset, ensuring smooth user interaction.

### Expected Outcome:
- The timer functionality should work only on designated websites (e.g., YouTube).
- Increment and decrement buttons should work as expected, with visual feedback provided.
- The reset button should work without reloading the page, and the user should be able to set a new timer after reset.

## Additional Notes:
- Ensure the extension continues to work seamlessly without introducing new issues after the changes.

I have also made a pull request for that. Please accept it.

**Comment by FerdausPolok** [comment]
Hello @tanushrigoel! Reason for closing the issue?
